language: node_js
node_js:
  - 10
cache:
  yarn: true

#install:
#  - yarn install
#
#directories:
#  - ./backend/node_modules
#  - ./frontend/host-app/node_modules
#  - ./frontend/guest-app/node_modules
#  - ./frontend/main-app/node_modules

matrix:
  include:
    - name: backend
      script:
        - yarn install:backend
        - yarn test:backend

    - name: frontend guest-app
      script:
        - yarn install:frontend:guest-app
        - yarn test:frontend:guest-app

    - name: frontend main-app
      script:
        - yarn install:frontend:main-app
        - yarn test:frontend:main-app

    - name: frontend host-app
      script:
        - yarn install:frontend:host-app
        - yarn test:frontend:host-app

