language: node_js
node_js:
  - 10
cache:
  yarn: true

#install:
#  - yarn install

jobs:
  include:
    - stage: install
      name: install backend
      script: yarn install:backend
    -
      name: install frontend host-app
      script: yarn install:frontend:host-app
    -
      name: install frontend guest-app
      script: yarn install:frontend:guest-app
    -
      name: install frontend main-app
      script: yarn install:frontend:main-app

    - stage: test
      name: test backend
      script: yarn test:backend
    -
      name: test frontend host-app
      script: yarn test:frontend:host-app
    -
      name: test frontend main-app
      script: yarn test:frontend:main-app
    -
      name: test frontend guest-app
      script: yarn test:frontend:guest-app

    - stage: build
      script: yarn build
