language: node_js
node_js:
  - 10
cache:
  yarn: true

install:
  - yarn install

jobs:
  include:
    - stage: test
      name: backend
      script: yarn test:backend
    -
      name: frontend host-app
      script: yarn test:frontend:host-app
    -
      name: frontend main-app
      script: yarn test:frontend:main-app
    -
      name: frontend guest-app
      script: yarn test:frontend:guest-app

    - stage: build
      script: yarn build
